const menu = [
  {
    id: 1,
    title: "buttermilk pancakes",
    category: "breakfast",
    price: 15.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJ_a9SK1_4ZTe5iXN2qWpnxkvQ6nxbiA7F3g&usqp=CAU",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: "diner double",
    category: "lunch",
    price: 13.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDQK4mKaqph2StQpArVtOko40SWH4Ez1Asal6zgZEMhcArbL8gOIuKQnIddw_F9vTLSkE&usqp=CAU",
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: "godzilla milkshake",
    category: "shakes",
    price: 6.99,
    img: "https://lovingitvegan.com/wp-content/uploads/2019/09/Vegan-Protein-Shake-Square.jpg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: "country delight",
    category: "breakfast",
    price: 20.99,
    img: "https://iamafoodblog.b-cdn.net/wp-content/uploads/2019/02/full-english-7355w-2-1024x683.jpg",
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: "egg attack",
    category: "lunch",
    price: 22.99,
    img: "https://img.delicious.com.au/6FWApqp6/w759-h506-cfill/del/2015/10/chicken-kiev-with-cabbage-slaw-15956-2.jpg",
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: "oreo dream",
    category: "shakes",
    price: 18.99,
    img: "https://tmbidigitalassetsazure.blob.core.windows.net/toh/GoogleImagesPostCard/Chocolate-Peanut-Butter-Shakes_EXPS_FT19_245766_F_1008_1.jpg",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: "bacon overflow",
    category: "breakfast",
    price: 8.99,
    img: "https://images.immediate.co.uk/production/volatile/sites/30/2017/08/smoothie-bowl-3a8632c.jpg",
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: "american classic",
    category: "lunch",
    price: 12.99,
    img: "https://www.heartfoundation.org.au/getmedia/bec2af45-93c7-4564-82ea-197d89595d9b/Cajun-beef-poke-bowl-01.jpg",
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: "green shake",
    category: "shakes",
    price: 16.99,
    img: "https://hips.hearstapps.com/hmg-prod/images/delish-200908-shamrock-shake-005-ab-1629317331.jpg?crop=0.593xw:0.887xh;0.0929xw,0.113xh&resize=1200:*",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 10,
    title: "hot beff",
    category: "dinner",
    price: 20.0,
    img: "https://st.depositphotos.com/1432537/1873/i/950/depositphotos_18738791-stock-photo-beff-steak-tournedos-with-grilled.jpg",
    desc: "Hot Beff is a special dish that brings together bold and passionate flavors. This unique recipe combines",
  }
];
export default menu;
